name: Cypress - PR SMOKE TEST

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Checkout Dev Repo
        uses: actions/checkout@v2

      - name: Parse env variables to json

        uses: jwsi/secret-parser@v1

        with:
          filename: cypress/config/git.json
          secret-name: important_value
          secret-value: ${{ secrets.important_value }}

      - name: Run Test

        uses: cypress-io/github-action@v2

        with:
          command: npm run git:stg
