name: Cypress - PR SMOKE TEST

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Checkout Dev Repo
        uses: actions/checkout@v2

      - name: Run Test

        uses: cypress-io/github-action@v2

        with:
          command: npm run cy:git

        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
